### ISSUE TITLE
Installation fails on Xcode < 7

### ISSUE THREAD

**Issue by scottdixon** [appium/appium-doctor#10]
socket.io install fails when compiling using Xcode 6.4 or below. More info: https://github.com/Homebrew/homebrew/issues/40653

Solutions: other than using Xcode 7, there's a symlink hack in the link above.

Ref: https://github.com/appium/appium/issues/5944

**Comment by imurchie** [comment]
This happens with `appium-doctor`? I can't get it to fail. I also can't find `socket.io` as a dependency.

**Comment by scottdixon** [comment]
Ohh that's right - from memory it was appium.app relying on socket.io to talk to appium doctor (so appium had socket.io as a dep). @jlipps knows more about this.

I don't think it's anything we need to address?

**Comment by jlipps** [comment]
yeah the issue was that we needed socket.io in conjunction with appium-doctor in appium. to get rid of socket.io we needed to remove appium-doctor as a dep.
