### ISSUE TITLE
Allow package to be used as a module

### ISSUE THREAD

**Issue by christian-bromann** [appium/appium-doctor#134]
Hey,

I would be interested to integrate `appium-doctor` into the WebdriverIO set-up wizard. For that I would love to make this tool consumable as a module so I can import and run it with arguments, e.g.:

```ts
import { check } from 'appium-doctor'

const result = await check(args)
```

Where `result` is an object with the results that allows one to print it somewhere or take own actions.

**Comment by KazuCocoa** [comment]
btw, this repo is going to be part of appium main repo as https://github.com/appium/appium/tree/master/packages/doctor in Appium 2.0

**Comment by christian-bromann** [comment]
Gotcha. Had a conversation in the Appium channel and we figured out a way forward. Cheers!
