### ISSUE TITLE
How to set the JAVA_HOME/bin directory?

### ISSUE THREAD

**Issue by wenshi11019** [appium/appium-doctor#17]
my .bash_profile file is 
`JAVA_HOME=$(/usr/libexec/java_home)`
`export JAVA_HOME`
`PATH=$PATH:$JAVA_HOME/bin`
`export PATH`

but I run the 'appium-doctor --android' command, give me the failed tips for "JAVA_HOME/bin"
`info AppiumDoctor ### Diagnostic starting ###`
`info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/gaojiewen/android-sdk`
`info AppiumDoctor  ✔ JAVA_HOME is set to:` `/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home`
`info AppiumDoctor  ✔ adb exists at: /Users/gaojiewen/android-sdk/platform-tools/adb`
`info AppiumDoctor  ✔ android exists at: /Users/gaojiewen/android-sdk/tools/android`
`info AppiumDoctor  ✔ emulator exists at: /Users/gaojiewen/android-sdk/tools/emulator`
`WARN AppiumDoctor  ✖ Bin directory of $JAVA_HOME is not set`
`info AppiumDoctor ### Diagnostic completed, one fix needed. ###`
`info AppiumDoctor `
`info AppiumDoctor ### Manual Fixes Needed ###`
`info AppiumDoctor The configuration cannot be automatically fixed, please do the following first:`
`WARN AppiumDoctor - Add '$JAVA_HOME/bin' to your PATH environment`
`info AppiumDoctor ###`
`info AppiumDoctor `
`info AppiumDoctor Bye, run appium-doctor again when all manual fixes have been applied!`
`info AppiumDoctor 
`

**Comment by imurchie** [comment]
This was caused by an error in the check. Upgrade to `appium-doctor@1.2.3` and it should all check out.
