### ISSUE TITLE
Running Doctor from Appium.app could not detect Mac OS X Version

### ISSUE THREAD

**Issue by BasThomas** [appium/appium-doctor#26]
Output:

```bash
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
[Error: Could not detect Mac OS X Version from sw_vers output: '10.12.3
']
```

Is this something that could cause issues elsewhere?

**Comment by imurchie** [comment]
This has been resolved. You need to upgrade the `appium-doctor` installation.

**Comment by BasThomas** [comment]
That doesn't seem to have resolved the issue.
<img width="573" alt="screen shot 2017-02-10 at 14 17 53" src="https://cloud.githubusercontent.com/assets/4190298/22828105/d13369e6-ef9b-11e6-9879-8a6b359e6c02.png">

**Comment by imurchie** [comment]
Those are two entirely different copies of `appium-doctor`. One is in `/usr/local/lib/node_modules/appium-doctor` (simlinked to `/usr/local/bin`) and the one you are running is in `/Applications/Appium.app/Contents/Resources/node_modules/appium-doctor`.

**Comment by BasThomas** [comment]
Right, but I can't manually update the `appium-doctor` version for `Appium.app`. Thanks for the explanation.

**Comment by imurchie** [comment]
If you really want to, you can, by going into `/Applications/Appium.app/Contents/Resources` and running `npm install appium-doctor`.

**Comment by BasThomas** [comment]
That doesn't solve it.
<img width="682" alt="screen shot 2017-02-10 at 14 53 26" src="https://cloud.githubusercontent.com/assets/4190298/22829046/c6e4181e-efa0-11e6-850c-b65d750ff3c5.png">

**Comment by imurchie** [comment]
Ah. It probably needs an updated `appium-support` library. You could update it if you want. I'm not sure if it will break anything else, though.

This is part of why the Appium.app is no longer supported.
