### ISSUE TITLE
When using NVM it doesn't detect node.exe

### ISSUE THREAD

**Issue by Humberd** [appium/appium-doctor#33]
I use NVM for Windows for versioning nodejs. When running `where node` it spits out these values

```
$ where node

F:\Tools\nodejs\node.exe
C:\Program Files\nodejs\node.exe
C:\Program Files\Microsoft MPI\Bin\node.exe
```
It creates a symlink from C drive to F drive. I also have another binary called node.
And now we have a collision.
https://github.com/appium/appium-doctor/blob/master/lib/node-detector.js#L39. 
```javascript
let nodePath = stdout.replace(/[\n\r]/g, "");
```
Here we concatenate those paths, which results in this mess: `F:\Tools\nodejs\node.exeC:\Program Files\nodejs\node.exeC:\Program Files\Microsoft MPI\Bin\node.exe`.

Which the next line always returns false.
```javascript
if (await fs.exists(nodePath)) {
```
And thus always failing to detect node

**Comment by jlipps** [comment]
Thanks for the report @Humberd. What I think is going on is this: on *nix systems, the `which` command (equivalent of `where` on windows), always only returns one line. Thus the regex replace you pointed out is really designed as a string trim, if I were to guess.

Sounds like the solution is to first split the response on a newline and take only the first result, owing to the differences between `where` and `which`.
