### ISSUE TITLE
Appium Doctor: why it claims xcode not install while I installed xcode indeed?

### ISSUE THREAD

**Issue by Sayalic0** [appium/appium-doctor#92]
Please check here:

https://stackoverflow.com/q/59588040/1291716

**Comment by KazuCocoa** [comment]
What the output of `xcode-select -p` and `xcrun simctl help`?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-doctor/blob/c726c4e7659ce32e2302f57012e44732974fb39b/lib/ios.js#L19-L31 is the logic. The result depends on the result of `xcrun simctl help` and `xcode-select -p`
