### ISSUE TITLE
appim-doctor not working 

### ISSUE THREAD

**Issue by andersonmann** [appium/appium-doctor#93]
Hello,
I'm trying run appium doctor but the error below happens.
Someone can help?

macOS Mojave: 10.14.6
sh-3.2# npm -v
6.13.4
sh-3.2# node -v
v12.14.1
sh-3.2# appium-doctor
info AppiumDoctor Appium Doctor v.1.13.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 12.14.1
Error: Command 'ffmpeg -version' exited with code null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/appium-doctor/node_modules/teen_process/lib/exec.js:113:19)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  stdout: '',
  stderr: 'dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib\n' +
    '  Referenced from: /usr/local/bin/ffmpeg\n' +
    '  Reason: image not found\n',
  code: null
}
sh-3.2#

**Comment by andersonmann** [comment]
``

**Comment by KazuCocoa** [comment]
Did the ffmpeg command work on your environment without errors?
appium-doctor check the installed version by `ffmpeg -version`. so, I wondered if the command had worked well on your env

**Comment by KazuCocoa** [comment]
The cause is ffmpeg installation, it looks
